# These are supported funding model platforms

github: real-airbauer
patreon: # Replace with a single Patreon username
open_collective: airbauer
ko_fi: airbauer
tidelift: # Replace with a single Tidelift platform-name/package-name e.g., npm/babel
community_bridge: # Replace with a single Community Bridge project-name e.g., cloud-foundry
custom: # Replace with a single custom sponsorship URL
